import { notFound } from "next/navigation";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { requireUser } from "@/lib/auth";

const modules: Record<string, { title: string; description: string }> = {
  sales: { title: "Sales", description: "Post daily shop sales, returns, COGS, bills, and customer counts." }, shops: { title: "Shops", description: "Manage branches, managers, targets, status, and access." }, products: { title: "Products", description: "Maintain product categories and category-level performance." }, expenses: { title: "Expenses", description: "Separate shop, central, and personal expenses with allocation visibility." }, profit: { title: "Profit & Margins", description: "Analyse gross profit, operating profit, withdrawals, and contributions." }, suppliers: { title: "Suppliers", description: "Manage supplier profiles, terms, bills, payments, and ledger balances." }, bills: { title: "Bills", description: "Record supplier invoices and track bill-level outstanding." }, payments: { title: "Payments", description: "Allocate supplier payments across one or more bills." }, ledger: { title: "Supplier Ledger", description: "Review immutable debits, credits, allocations, and reversals." }, outstanding: { title: "Outstanding", description: "Track overdue, due-today, and aging liabilities." }, "daily-closing": { title: "Daily Closing", description: "Reconcile expected and counted cash with approval accountability." }, "cash-flow": { title: "Cash Flow", description: "Review cash inflows, outflows, withdrawals, and adjustments." }, targets: { title: "Targets", description: "Compare sales, profit, expense, and margin targets with actuals." }, reports: { title: "Reports", description: "Generate filtered operational and financial reports." }, documents: { title: "Documents", description: "Secure supporting documents, invoices, receipts, and payment proof." }, alerts: { title: "Alerts", description: "Configure thresholds for sales, margins, expenses, overdue bills, and cash variance." }, users: { title: "Users", description: "Manage roles, account status, and shop assignments." }, "audit-logs": { title: "Audit Logs", description: "Inspect who changed financial data, when, why, and what changed." }, settings: { title: "Settings", description: "Manage business, account, security, and system configuration." },
};

export default async function ModulePage({ params }: { params: Promise<{ module: string }> }) {
  const { module } = await params; const config = modules[module]; if (!config) notFound(); const user = await requireUser();
  return <AppShell user={user}><div className="mx-auto max-w-6xl"><p className="label">LK Ledger Book</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.045em]">{config.title}</h1><p className="mt-3 max-w-2xl text-[#66736b]">{config.description}</p><div className="card mt-8 p-8"><h2 className="text-xl font-semibold">No records yet</h2><p className="mt-2 text-sm text-[#66736b]">This workspace is connected to PostgreSQL and ready for authorised data entry. Records will appear here with server-side filtering and pagination.</p><Link href="/dashboard" className="button-primary mt-6 inline-flex items-center">Back to dashboard</Link></div></div></AppShell>;
}
